name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Update version in __init__.py
      run: |
        VERSION=$(echo ${{ github.event.release.tag_name }} | cut -c2-)
        sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" creditagricole_particuliers/__init__.py

    - name: Build Python package
      run: |
        python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
